name: execute-queries

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Query folder to execute (relative to library)'
        required: true
        type: string

jobs:
  execute:
    name: Execute queries in ${{ github.event.inputs.folder }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      folder: library/${{ github.event.inputs.folder }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate folder existence
        run: |
          if [ ! -d ${{ env.folder }} ]; then
            echo "Folder ${{ env.folder }} does not exist"
            exit 1
          fi

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install log-analytics extension
        run: |
          az config set extension.dynamic_install_allow_preview=true
          az extension add --name log-analytics
          az extension update --name log-analytics

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Execute queries
        run: |
          .github/scripts/execute_queries.py ${{ env.folder }} \
            -w ${{ secrets.WORKSPACE_ID }}
