name: execute-queries

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Query folder to execute (relative to library)'
        required: true
        type: string

jobs:
  execute:
    name: Execute queries in ${{ github.event.inputs.folder }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      folder: library/${{ github.event.inputs.folder }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate folder existence
        run: |
          if [ ! -d ${{ env.folder }} ]; then
            echo "Folder ${{ env.folder }} does not exist"
            exit 1
          fi

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install log-analytics extension
        run: |
          az config set extension.dynamic_install_allow_preview=true
          az extension add --name log-analytics
          az extension update --name log-analytics

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/kql_query_executor/requirements.txt

      - name: Execute queries
        run: |
          python .github/scripts/kql_query_executor/main.py \
            --folder ${{ env.folder }} \
            --workspace-id ${{ secrets.WORKSPACE_ID }} \
            --schema kql-config-schema.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Query-Results
          path: query-results
